export const ADMIN_ROUTE = '/admin'
export const MAIN_ROUTE = '/'
export const FAQ_ROUTE = '/faq'
export const TEACHERS_ROUTE = '/teachers'
export const NEWS_ROUTE = '/news'
export const ACHIEVES_ROUTE = '/achieves'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
